services:
  msc-user:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8080:8080"  
    environment:
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
    depends_on:
      - db  

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_DB: msc_user  
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: postgres  
